use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("posts.rs");

    // Get the workspace root (content crate is in crates/content)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = Path::new(&manifest_dir).parent().unwrap().parent().unwrap();
    let posts_dir = workspace_root.join("content").join("posts");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs\n\n");
    code.push_str("pub const POSTS: &[(&str, &str)] = &[\n");

    if posts_dir.exists() {
        let mut entries: Vec<_> = fs::read_dir(&posts_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path()
                    .extension()
                    .map(|ext| ext == "md")
                    .unwrap_or(false)
            })
            .collect();

        // Sort by filename for consistent ordering
        entries.sort_by_key(|e| e.path());

        for entry in entries {
            let path = entry.path();
            let slug = path.file_stem().unwrap().to_str().unwrap();
            let relative_path = path.strip_prefix(workspace_root).unwrap();

            code.push_str(&format!(
                "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../{}\"))),\n",
                slug,
                relative_path.display()
            ));

            // Tell Cargo to rerun if this file changes
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    code.push_str("];\n");

    fs::write(&dest_path, code).unwrap();

    // Rerun if posts directory changes
    println!("cargo:rerun-if-changed={}", posts_dir.display());
}
