[application]
name = "dioxus-blog"
default_platform = "web"

[web.app]
title = "Dioxus Markdown Blog"

[web.watcher]
reload_html = true
watch_path = ["apps", "crates", "content"]

[web.resource.dev]
style = []

[web.resource.release]
style = []
